title: Topgedgets
author: Darshan Patel
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This Project is based on Wordpress. This is a blog base Website Where more than 20 Article post are Available. Which is written by me.
  And I also do SEO (Search Engine Optimization) for this Articles. Link : [Topgedgets](http://topgedgets.unaux.com/)

# social links
twitter_username: Darshan Patel # DO NOT include the @ character, or else the build will fail!
github_username:  DarshuPatel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
